import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy',
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="container mx-auto px-4 py-8 md:py-12">
        <header className="mb-8 md:mb-12 text-center">
          <h1 className="text-3xl md:text-4xl font-bold">Privacy Policy</h1>
          <p className="text-muted-foreground mt-2">Last updated: {new Date().toLocaleDateString()}</p>
        </header>

        <main className="prose prose-sm sm:prose lg:prose-lg xl:prose-xl dark:prose-invert mx-auto">
          <p>Welcome to UniTaskAI! We are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our application.</p>

          <section>
            <h2 id="what-data-is-collected">1. What Data is Collected</h2>
            <p>We collect the following types of information:</p>
            <ul>
              <li><strong>Prompts you enter:</strong> This includes all text and commands you input into the chatbot, even the weird stuff.</li>
              <li><strong>Outputs generated by the chatbot:</strong> The responses and content generated by the AI based on your prompts.</li>
              <li><strong>Account information:</strong> This includes your email address, username, and payment details if you subscribe to paid services.</li>
              <li><strong>Device data:</strong> We may collect your IP address, browser type, operating system, and approximate location derived from your IP address.</li>
              <li><strong>Usage data:</strong> Information about your interactions with our service, such as when you use it, how often, and which features you engage with.</li>
            </ul>
          </section>

          <section>
            <h2 id="how-your-data-is-used">2. How Your Data is Used</h2>
            <p>Your data is used for the following purposes:</p>
            <ul>
              <li><strong>To provide and improve the AI service:</strong> This includes personalizing your experience, training our models (unless you opt-out where available), and enhancing the functionality and accuracy of our services.</li>
              <li><strong>To analyze usage and troubleshoot problems:</strong> We use data to understand how our service is being used, to identify and fix issues, and to improve performance.</li>
              <li><strong>For marketing:</strong> We may use your information to inform you about new features, promotions, or other services that may be of interest to you (you can opt-out of marketing communications).</li>
              <li><strong>For legal compliance:</strong> We may use your data to comply with applicable laws, regulations, court orders, or other legal processes (e.g., responding to a court order because you asked for a way to summon Bigfoot).</li>
            </ul>
            <p>You have the power to delete chats or your whole account. Please see Section 6 for more details on your rights.</p>
          </section>
          
          <section>
            <h2 id="who-the-data-is-shared-with">3. Who the Data is Shared With</h2>
            <p>We may share your information with the following parties:</p>
            <ul>
              <li><strong>Third-party service providers:</strong> We may share data with vendors who perform services on our behalf, such as cloud hosting, payment processing, data analytics, and customer support. These providers are contractually obligated to protect your data.</li>
              <li><strong>Affiliates within the company "family":</strong> If applicable, we may share information with our parent companies, subsidiaries, joint ventures, or other companies under common control.</li>
              <li><strong>Legal authorities:</strong> We may disclose your information if required to do so by law or in response to valid requests by public authorities (e.g., a court or government agency).</li>
              <li><strong>Advertising or analytics partners:</strong> We may share aggregated or de-identified information with partners for analytics and advertising purposes. This information does not directly identify you.</li>
            </ul>
          </section>

          <section>
            <h2 id="your-controls-and-rights">4. Your Controls and Rights</h2>
            <p>You have certain rights regarding your personal data, including:</p>
            <ul>
              <li><strong>Access, correct, or delete your data:</strong> You can request access to the personal data we hold about you, ask for corrections to inaccurate data, or request the deletion of your data or your entire account.</li>
              <li><strong>Data portability:</strong> You have the right to request a copy of your data in a machine-readable format to take it with you.</li>
              <li>To exercise these rights, please contact us through the methods provided in our application or on our website.</li>
            </ul>
          </section>

          <section>
            <h2 id="security-and-regional-compliance">5. Security and Regional Compliance</h2>
            <p><strong>Security:</strong> We implement "reasonable" security measures to protect your information from unauthorized access, use, or disclosure. However, please be aware that no security measures are perfect or impenetrable, and we cannot guarantee the absolute security of your data.</p>
            <p><strong>Children's privacy:</strong> Our service is not intended for individuals under the age of 13. We do not knowingly collect personal information from children under 13. If we become aware that a child under 13 has provided us with personal information, we will take steps to delete such information.</p>
            <p><strong>Regional Compliance:</strong> We strive to comply with applicable data protection laws in the regions where we operate. Depending on your location, you may have additional rights under local laws (e.g., GDPR, CCPA).</p>
          </section>

          <section>
            <h2 id="changes-to-this-policy">6. Changes to This Privacy Policy</h2>
            <p>We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date. You are advised to review this Privacy Policy periodically for any changes.</p>
          </section>

          <section>
            <h2 id="contact-us">7. Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, please contact us at [Your Contact Email or Link to Contact Form].</p>
          </section>
        </main>

        <footer className="mt-12 text-center text-sm text-muted-foreground">
          <p>&copy; {new Date().getFullYear()} UniTaskAI. All rights reserved.</p>
        </footer>
      </div>
    </div>
  );
} 