import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="container mx-auto px-4 py-8 md:py-12">
        <header className="mb-8 md:mb-12 text-center">
          <h1 className="text-3xl md:text-4xl font-bold">Terms of Service</h1>
          <p className="text-muted-foreground mt-2">Last updated: {new Date().toLocaleDateString()}</p>
        </header>

        <main className="prose prose-sm sm:prose lg:prose-lg xl:prose-xl dark:prose-invert mx-auto">
          <p>Welcome to UniTaskAI! These Terms of Service (&quot;Terms&quot;) govern your use of our application, website, and services. By accessing or using UniTaskAI, you agree to be bound by these Terms.</p>

          <section>
            <h2 id="acceptance-of-terms">1. Acceptance of Terms</h2>
            <p>By accessing or using our Service, you agree to be bound by these Terms. If you disagree with any part of the Terms, then you may not access the Service.</p>
          </section>

          <section>
            <h2 id="changes-to-terms">2. Changes to Terms</h2>
            <p>We reserve the right to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days&apos; notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
          </section>

          <section>
            <h2 id="user-accounts">3. User Accounts</h2>
            <p>When you create an account with us, you must provide information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account.</p>
            <p>You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.</p>
            <p>You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p>
          </section>

          <section>
            <h2 id="intellectual-property">4. Intellectual Property</h2>
            <p>The Service and its original content, features, and functionality are and will remain the exclusive property of UniTaskAI and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries.</p>
            <p>Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of UniTaskAI.</p>
          </section>

          <section>
            <h2 id="user-generated-content">5. User Generated Content</h2>
            <p>You retain any and all of your rights to any content you submit, post, or display on or through the Service (&quot;User Content&quot;). By submitting User Content to the Service, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, adapt, publish, translate, and distribute your User Content in any existing or future media.</p>
            <p>You represent and warrant that your User Content does not violate copyright, trademark, or other intellectual property rights of any third party. You agree not to submit User Content that is unlawful, defamatory, harassing, threatening, or that encourages conduct that would be considered a criminal offense.</p>
          </section>
          
          <section>
            <h2 id="use-of-ai-generated-content">6. Use of AI-Generated Content</h2>
            <p>Content generated by our AI service is provided for informational purposes only. While we strive for accuracy and quality, we do not guarantee that the AI-generated content will be error-free or suitable for any specific purpose.</p>
            <p>You are solely responsible for reviewing, verifying, and validating any AI-generated content before using it for any purpose, especially in professional, academic, or commercial contexts.</p>
            <p>You retain full intellectual property rights to AI-generated content created through your specific prompts, subject to our license to use such content as described in Section 5.</p>
          </section>

          <section>
            <h2 id="prohibited-uses">7. Prohibited Uses</h2>
            <p>You agree not to use the Service:</p>
            <ul>
              <li>In any way that violates any applicable national or international law or regulation.</li>
              <li>To exploit, harm, or attempt to exploit or harm minors in any way.</li>
              <li>To generate or disseminate false, harmful, or misleading information.</li>
              <li>To attempt to circumvent any content filtering techniques we employ.</li>
              <li>To attempt to gain unauthorized access to our servers, systems, or networks.</li>
              <li>To interfere with or disrupt the integrity or performance of the Service.</li>
              <li>To create or distribute malware, viruses, or other harmful computer code.</li>
              <li>For any unlawful or fraudulent purpose, or to engage in deceptive practices.</li>
            </ul>
          </section>

          <section>
            <h2 id="termination">8. Termination</h2>
            <p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
            <p>Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service or contact us to request account deletion.</p>
          </section>

          <section>
            <h2 id="limitation-of-liability">9. Limitation of Liability</h2>
            <p>In no event shall UniTaskAI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:</p>
            <ul>
              <li>Your access to or use of or inability to access or use the Service;</li>
              <li>Any conduct or content of any third party on the Service;</li>
              <li>Any content obtained from the Service; and</li>
              <li>Unauthorized access, use, or alteration of your transmissions or content.</li>
            </ul>
          </section>

          <section>
            <h2 id="disclaimer">10. Disclaimer</h2>
            <p>Your use of the Service is at your sole risk. The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement, or course of performance.</p>
          </section>

          <section>
            <h2 id="governing-law">11. Governing Law</h2>
            <p>These Terms shall be governed and construed in accordance with the laws of [Your Country/State], without regard to its conflict of law provisions.</p>
            <p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect.</p>
          </section>

          <section>
            <h2 id="contact-us">12. Contact Us</h2>
            <p>If you have any questions about these Terms, please contact us at [Your Contact Email].</p>
          </section>
        </main>

        <footer className="mt-12 text-center text-sm text-muted-foreground">
          <p>&copy; {new Date().getFullYear()} UniTaskAI. All rights reserved.</p>
        </footer>
      </div>
    </div>
  );
}